### ISSUE TITLE
Can not restore Apple AppStore purchase

### ISSUE THREAD

**Issue by Qteb** [racompass/racompass#3]
Error message:
`Failed to restore purchases, please try again later. certificate has expired`

Also, a have active subscription in my AppStore account.
Screenshots in attachment.

![image](https://user-images.githubusercontent.com/877437/138116008-e7e87610-eda1-4eea-b8ec-79269167ad40.png)
![image](https://user-images.githubusercontent.com/877437/138116078-70ba1235-97b0-470d-b5b6-d893c0200ab9.jpeg)

**Comment by appsnano** [comment]
Thank you for purchasing Racompass.
We found out the error which is SSL certificate issue.
And the error fixed.
Please try to restore again.
Thanks!

**Comment by Qteb** [comment]
Fixed.
Thx.
