### ISSUE TITLE
Deleted keys are not removed from list

### ISSUE THREAD

**Issue by lycwed** [racompass/racompass#4]
When the project flush cache, it do not refresh the interface and when we click on the key, it displays 'The key "_KEY_" does not exists.'

**Comment by appsnano** [comment]
I'd like to know the interface not refreshing is that mean sending a command `FLUSHDB` / `FLUSHALL` from your application, and the "Key Live Update" option is ON?

if yes,....
According to [Redis Doc](https://redis.io/docs/manual/keyspace-notifications), there is no notification for `FLUSHDB` / `FLUSHALL`.

I'm thinking, try to make "Key Live Update" combines  **Keyspace Notifications** with `MONITOR` in next version.

**Comment by lycwed** [comment]
Ok I try empty cache by using del instead ok flush and it works great!
Maybe you should add a refresh button in the list panel.

**Comment by appsnano** [comment]
Updated since 1.2.0~
<img width="320" alt="KeySpace+Monitor" src="https://user-images.githubusercontent.com/43163425/236680524-a75f51d0-694f-4be4-89d0-4813530a0084.png">
