### ISSUE TITLE
Customize preferences

### ISSUE THREAD

**Issue by lycwed** [racompass/racompass#5]
It would be great to have:
- dark mode
- font family change

**Comment by appsnano** [comment]
For the dark mode, i'm working on it in current stage~
but the font family changing may take more time to test UI design.~~

**Comment by lycwed** [comment]
For font family If you use monospaced font normally it should not be a big thing. Anyway your app is already great!

**Comment by ibis-management** [comment]
Dark Mode Please

**Comment by appsnano** [comment]
Updated since 1.2.0~ Thanks!
<img width="483" alt="Preferences" src="https://user-images.githubusercontent.com/43163425/236680644-9aa7b748-5cf4-4f6f-92c3-eca0d7d29d18.png">
