### ISSUE TITLE
502 Error is Preventing Purchase Restoration

### ISSUE THREAD

**Issue by vanpyrzericj** [racompass/racompass#7]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/4707908/230739508-4fb2b81e-7f2a-432f-aac4-fdf4c276b05a.png">

**Comment by appsnano** [comment]
Thank you for purchasing our product.
We have just figured out the error that occurred during provider maintenance.
And the issues fixed.
Please try to restore again.
Thanks!
